version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target:
      branch: "develop"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target:
      branch: "develop"

  - package-ecosystem: docker
    directory: /selenium-patches
    schedule:
      interval: daily
